apiVersion: apps/v1
kind: Deployment
metadata:
  name: items
spec:
  selector:
    matchLabels:
      app: items
  replicas: 3
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
        - name: items
          image: "items"
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: items
spec:
  selector:
    app: items
  ports:
  - protocol: TCP
    port: 3000
    targetPort: http
